name: Basic Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # TEST
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
        env:
          CI: true

  # COVERAGE
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests

  # PRETTIER
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Check format using Prettier
        run: npx prettier --check .

  # BUILD
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
