name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  # E2E TEST
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          [
            cached-translations,
            custom-backend,
            custom-language-selection,
            custom-location,
            simple,
            typescript,
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2

      - name: Install
        run: yarn install --frozen-lockfile

      - run: npx playwright install chromium

      - name: Build ni18n
        run: yarn build:esm

      - name: Install local dependencies on ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn install --frozen-lockfile

      - name: Build ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn build

      - name: Serve ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn start &

      - name: Run E2E for ${{ matrix.example }}
        env:
          EXAMPLE_FOLDER: ${{ matrix.example }}
        run: yarn test:e2e
