# Run only a subset of e2e tests during PR so it doesn't eat up the quota
name: PR E2E Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/assets/**'
      - 'scripts/**/*'
      - '**/*.md'
      - '.git*'
      - '.editor*'
      - '.npm*'
      - '.prettier*'
      - 'jest.*'

jobs:
  # E2E TEST
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [typescript]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.example }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.example }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile

      - run: npx playwright install chromium

      - name: Build ni18n
        run: yarn build:esm

      - name: Install local dependencies on ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn install --frozen-lockfile

      - name: Build ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn build

      - name: Serve ${{ matrix.example }}
        run: cd examples/${{ matrix.example }} && yarn start &

      - name: Run E2E for ${{ matrix.example }}
        run: yarn test:e2e
