name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release Type - patch | minor | major | 1.2.3
        type: string
        default: patch
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.email "juniorquintas@gmail.com"
          git config user.name "Jose Quintas"
      - name: Use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Tag
        run: yarn version --new-version ${{ github.event.inputs.version }} --preid rc

      - name: Push Tag
        run: git push --follow-tags

      - name: Publish
        if: ${{ github.event.inputs.version != 'prerelease' && github.event.inputs.version != 'prepatch' && github.event.inputs.version != 'preminor' && github.event.inputs.version != 'premajor'}}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Beta
        if: ${{ github.event.inputs.version == 'prerelease' || github.event.inputs.version == 'prepatch' || github.event.inputs.version == 'preminor' || github.event.inputs.version == 'premajor'}}
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
